name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le projet
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t formation-app .

    - name: Run container
      run: docker run -d -p 8080:80 formation-app